[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "The MetaSUB CAMP"
authors = [{name = "Braden Tierney", email = "btt4001@med.cornell.edu"}]
dynamic = ["version", "description"]
